parameters:

    # Ignore lists
    naneau.obfuscator.node_visitor.scramble_variable.ignore: []
    naneau.obfuscator.node_visitor.scramble_private_method.ignore: []
    naneau.obfuscator.node_visitor.scramble_private_property.ignore: []
    naneau.obfuscator.node_visitor.scramble_use.ignore: []

services:

    # Obfuscator
    naneau.obfuscator:
        class: Naneau\Obfuscator\Obfuscator
        calls:
            - [setParser, [@naneau.obfuscator.parser]]
            - [setTraverser, [@naneau.obfuscator.node_traverser]]
            - [setPrettyPrinter, [@naneau.obfuscator.pretty_printer]]
            - [setEventDispatcher, [@naneau.obfuscator.event_dispatcher]]

    # String scrambler
    naneau.obfuscator.scrambler:
        class: Naneau\Obfuscator\StringScrambler

    # Node traverser
    naneau.obfuscator.node_traverser:
        class: PhpParser\NodeTraverser
        calls:
            - [addVisitor, [@naneau.obfuscator.node_visitor.scramble_variable]]
            - [addVisitor, [@naneau.obfuscator.node_visitor.scramble_private_method]]

    # Variable scrambler
    naneau.obfuscator.node_visitor.scramble_variable:
        class: Naneau\Obfuscator\Node\Visitor\ScrambleVariable
        arguments:
             - @naneau.obfuscator.scrambler
        calls:
            - [addIgnore, [%naneau.obfuscator.node_visitor.scramble_variable.ignore%]]

    # Scramble private methods
    naneau.obfuscator.node_visitor.scramble_private_method:
        class: Naneau\Obfuscator\Node\Visitor\ScramblePrivateMethod
        arguments:
             - @naneau.obfuscator.scrambler
        calls:
            - [addIgnore, [%naneau.obfuscator.node_visitor.scramble_private_method.ignore%]]

    # Scramble private properties
    naneau.obfuscator.node_visitor.scramble_private_property:
        class: Naneau\Obfuscator\Node\Visitor\ScramblePrivateProperty
        arguments:
             - @naneau.obfuscator.scrambler
        calls:
            - [addIgnore, [%naneau.obfuscator.node_visitor.scramble_private_property.ignore%]]

    # Scramble use statements
    naneau.obfuscator.node_visitor.scramble_use:
        class: Naneau\Obfuscator\Node\Visitor\ScrambleUse
        arguments:
             - @naneau.obfuscator.scrambler
        calls:
            - [addIgnore, [%naneau.obfuscator.node_visitor.scramble_use.ignore%]]

    # Name resolver (needed before scramble_use)
    naneau.obfuscator.node_visitor.name_resolver:
        class: PhpParser\NodeVisitor\NameResolver

    # Parser
    naneau.obfuscator.parser:
        class: PhpParser\Parser
        arguments:
            - @naneau.obfuscator.lexer

    # Lexer
    naneau.obfuscator.lexer:
        class: PhpParser\Lexer

    # Pretty printer
    naneau.obfuscator.pretty_printer:
        class: PhpParser\PrettyPrinter\Standard

    # Event dispatcher
    naneau.obfuscator.event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container
